// The generated half of the mocked library — what agent run r-042 filed.
// Every provenance points at real ids so lineage links resolve.

import type { Asset } from "./types";

export const GENERATED_ASSETS: Asset[] = [
  {
    id: "aud-1",
    kind: "audio",
    title: "Trailer VO — cold open",
    mime: "audio/wav",
    bytes: 1_900_000,
    createdAt: "2026-08-09T14:03:00Z",
    durationS: 11.4,
    caption:
      "Low, unhurried female narration: “Every city keeps one door unlocked. Ours was on the water.” Tense, close-mic read.",
    captionStatus: "written",
    tags: ["narration", "take", "glass-harbor"],
    collection: "Glass Harbor / Trailer v2",
    provenance: {
      source: "generated",
      model: "pocket-tts:marla",
      prompt: "Cold-open line, tense/low, 12s budget",
      runId: "r-042",
      stepId: "s4",
      parentIds: ["scr-1"],
    },
    tone: "from-cyan-900/60 via-slate-900 to-slate-950",
  },
  {
    id: "aud-2",
    kind: "audio",
    title: "Trailer VO — heist beat",
    mime: "audio/wav",
    bytes: 2_400_000,
    createdAt: "2026-08-09T14:04:00Z",
    durationS: 14.8,
    caption:
      "Same voice, faster pulse: names the crew and the one rule they break. Ends clipped, on purpose, for the cut.",
    captionStatus: "written",
    tags: ["narration", "take", "glass-harbor"],
    collection: "Glass Harbor / Trailer v2",
    provenance: {
      source: "generated",
      model: "pocket-tts:marla",
      prompt: "Heist-beat lines, urgency up, 15s budget",
      runId: "r-042",
      stepId: "s4",
      parentIds: ["scr-1"],
    },
    tone: "from-cyan-900/60 via-slate-900 to-slate-950",
  },
  {
    id: "img-3",
    kind: "image",
    title: "Poster concept A — the unlocked door",
    mime: "image/png",
    bytes: 6_200_000,
    createdAt: "2026-08-09T14:06:00Z",
    dims: "1024×1536",
    caption:
      "Night-blue one-sheet: a lone silhouette at a harbor gate, sodium-orange keyline, title block bottom third.",
    captionStatus: "written",
    tags: ["poster", "concept"],
    collection: "Glass Harbor / Trailer v2",
    provenance: {
      source: "generated",
      model: "imagen-3",
      prompt: "Noir heist one-sheet, harbor gate at night, single silhouette",
      runId: "r-042",
      stepId: "s5",
      parentIds: ["img-1"],
    },
    tone: "from-indigo-950 via-slate-900 to-slate-950",
  },
  {
    id: "img-4",
    kind: "image",
    title: "Poster concept B — crane skyline",
    mime: "image/png",
    bytes: 5_900_000,
    createdAt: "2026-08-09T14:06:30Z",
    dims: "1024×1536",
    caption:
      "High-contrast skyline of cranes as prison bars; the crew as five small figures crossing the apron.",
    captionStatus: "written",
    tags: ["poster", "concept"],
    collection: "Glass Harbor / Trailer v2",
    provenance: {
      source: "generated",
      model: "imagen-3",
      prompt: "Crane skyline as bars, five figures, high contrast noir",
      runId: "r-042",
      stepId: "s5",
      parentIds: ["img-1"],
    },
    tone: "from-slate-800 via-slate-900 to-slate-950",
  },
  {
    id: "img-5",
    kind: "image",
    title: "Poster concept C — wet asphalt title",
    mime: "image/png",
    bytes: 6_800_000,
    createdAt: "2026-08-09T14:07:00Z",
    dims: "1024×1536",
    caption:
      "Title reflected in rain on black asphalt, no figures at all; the quietest of the three.",
    captionStatus: "written",
    tags: ["poster", "concept"],
    collection: "Glass Harbor / Trailer v2",
    provenance: {
      source: "generated",
      model: "imagen-3",
      prompt: "Title reflected in wet asphalt, no people, minimal noir",
      runId: "r-042",
      stepId: "s5",
      parentIds: ["img-1"],
    },
    tone: "from-cyan-950 via-slate-950 to-black",
  },
  {
    id: "vid-3",
    kind: "video",
    title: "trailer_rough_mux.mp4",
    mime: "video/mp4",
    bytes: 38_000_000,
    createdAt: "2026-08-09T14:11:00Z",
    durationS: 31,
    dims: "1920×1080",
    caption:
      "Rough trailer: cold open over the pier walk, heist beat over quick cuts. No score — the music step failed and the mux says so.",
    captionStatus: "written",
    tags: ["trailer", "rough-cut"],
    collection: "Glass Harbor / Trailer v2",
    provenance: {
      source: "generated",
      model: "ffmpeg-mux",
      runId: "r-042",
      stepId: "s7",
      parentIds: ["vid-1", "aud-1", "aud-2"],
    },
    tone: "from-slate-900 via-slate-950 to-black",
  },
];
