// SOUND — the headless surface of the sound store (lib/sound/).
//
//   npx tsx pipeline/sound.mts list [--kind music|sfx] [--verdict v] [--stage s] [--provider p] [--origin o] [--fixtures]
//   npx tsx pipeline/sound.mts generate --kind music --prompt "..." --duration 30 [--technique a,b]
//        [--op compose|plan|sfx] [--negative "..."] [--genre a,b] [--mood a,b] [--instrument a,b]
//        [--category impacts] [--loop] [--influence 0.7] [--tempo 92] [--key "A minor"] [--title "..."]
//   npx tsx pipeline/sound.mts judge <takeId> --verdict kept|rejected|unjudged [--score melody=8,instrument_choice=7]
//        [--reasons off-brief,loop-seam] [--note "..."] [--stage pending|remaster|edit|finalized|none] [--group g] [--label l]
//   npx tsx pipeline/sound.mts finalized [--kind music|sfx] [--group g] [--label text]
//   npx tsx pipeline/sound.mts lessons [--kind music|sfx]
//   npx tsx pipeline/sound.mts knowledge [--check]
//
//   --json on any command: one JSON document on stdout, nothing else.
//   Exit 0 ok · 1 the operation failed · 2 usage.
//
// WHO THIS IS FOR. An agent working without a browser, in two directions:
// `generate` is how "tracks generated by an LLM through a provider" arrive in
// Triage (origin "agent", unjudged), and `finalized` is how an agent picks a
// track a person has finalized and labelled. Every --json shape is the HTTP
// contract's (lib/sound/types.ts); a failure is an exit code plus
// `{ "error": "..." }`, never prose to parse.
//
// IT OWNS NO LOGIC. The verbs are lib/sound/cli.ts (a function, so the offline
// probe can drive them without spawning tsx), and each verb is one call into
// lib/sound — the same calls the app/api/sound routes make. `generate` BILLS
// the music vendor, under the routes' own spend ceiling (lib/music/budget.ts).
//
// `lessons` LISTS and never writes: a lesson is confirmed by a person in the
// lab (POST /api/sound/lessons). `knowledge` regenerates knowledge/audio/ from
// the ledger; `--check` exits 1 when the committed files are stale.

import fs from "node:fs";
import path from "node:path";

const ROOT = path.resolve(import.meta.dirname, "..");

/** .env then .env.local, never clobbering an exported value — pipeline/publish.mts's loader. */
function loadEnv(root: string) {
  for (const f of [".env", ".env.local"]) {
    const at = path.join(root, f);
    if (!fs.existsSync(at)) continue;
    for (const line of fs.readFileSync(at, "utf8").split(/\r?\n/)) {
      if (!line || line.startsWith("#") || !line.includes("=")) continue;
      const i = line.indexOf("=");
      const k = line.slice(0, i).trim();
      const v = line.slice(i + 1).trim();
      if (v && process.env[k] === undefined) process.env[k] = v;
    }
  }
}
loadEnv(ROOT);
// the store, the ledger and the prompt files are cwd-relative (as in the server)
process.chdir(ROOT);

// imported after loadEnv, so a module that reads env at load sees the operator's
const { runSoundCli } = await import("../lib/sound/cli");

const code = await runSoundCli(process.argv.slice(2), {
  root: ROOT,
  out: (l) => console.log(l),
  err: (l) => console.error(l),
});
process.exit(code);
