// The fact table — run 1, verbatim from
// pipeline/runs/2026-08-11-why-bitcoin-price-does-not-rise/notebook.json,
// plus the three facts follow-up round 1 wrote back.
//
// Split out of notebook.ts because it is the half that GROWS: every follow-up
// round adds rows here and touches nothing else in the document.

import type { Fact } from "./types";

export const FACTS: Fact[] = [
  { id: "f-ath", claim: "Bitcoin's all-time high was $126,198.07 on 6 October 2025", loadBearing: true, source: "99bitcoins / investingnews price history", confidence: "high", asOf: "2025-10-06" },
  { id: "f-nov-crash", claim: "By 21 November 2025 it had fallen to $80,660 — a >30% drawdown in six weeks", loadBearing: true, source: "investingnews.com price history", confidence: "high", asOf: "2025-11-21" },
  { id: "f-now", claim: "In August 2026 Bitcoin trades near $60–65k, repeatedly capped at the $65,500–$67,000 region", loadBearing: true, source: "invezz, crypto.news, intellectia", confidence: "medium", confidenceNote: "price sources vary by a few thousand", asOf: "2026-08-10" },
  { id: "f-drawdown", claim: "That is a fall of nearly 50% from the October 2025 high", loadBearing: true, source: "coinpedia regulation timeline", confidence: "high", asOf: "2026-08" },
  { id: "f-sbr", claim: "Trump signed the executive order establishing a Strategic Bitcoin Reserve on 6 March 2025", loadBearing: true, source: "whitehouse.gov fact sheet", confidence: "high", asOf: "2025-03-06" },
  { id: "f-sbr-unbuilt", claim: "16 months later the White House concedes the long-term stockpile process is still being worked out, and agencies do not agree on how much BTC the US owns", loadBearing: true, source: "coindesk 2026-07-06, cryptoslate", confidence: "high", asOf: "2026-07-06", note: "The flagship policy win is, in practice, unimplemented. Strong irony beat." },
  { id: "f-genius", claim: "The GENIUS Act passed; regulators were replaced with crypto-friendly appointees; crypto access was expanded to retirement accounts", loadBearing: true, source: "coinpedia regulation timeline", confidence: "medium", asOf: "2026" },
  { id: "f-lth-distribution", claim: "Long-term holders realised 3.67 million BTC in profit in the $100,000–$126,000 range — a larger distribution than any previous cycle", loadBearing: true, source: "on-chain data via intellectia", confidence: "medium", confidenceNote: "single aggregator, not verified against Glassnode/CryptoQuant primary", asOf: "2026" },
  { id: "f-etf-lag", claim: "ETF inflows are not immediate spot demand: authorised participants often create and short ETF shares before buying the underlying bitcoin", loadBearing: true, source: "coindesk 2026-03-04, analyst explanation", confidence: "medium", confidenceNote: "mechanism reported by one analyst", asOf: "2026-03-04" },
  { id: "f-etf-absorbed", claim: "Inflows have been positive but insufficient: holders who bought near these levels use recoveries to reduce positions, so ETF buying is absorbed by sellers rather than lifting price", loadBearing: true, source: "invezz 2026-08-10", confidence: "medium", asOf: "2026-08-10" },
  { id: "f-mnav", claim: "Strategy's mNAV fell from 3.89x (Nov 2024) to below 1.0 — its market cap is worth less than the bitcoin it holds", loadBearing: true, source: "KuCoin, phemex, bitcoinworld", confidence: "high", asOf: "2026" },
  { id: "f-mstr-drop", claim: "MSTR fell ~70% between August 2025 and February 2026; the company reported a $12.4bn loss in Q4 2025", loadBearing: true, source: "bydfi / decrypt", confidence: "medium", asOf: "2026-02" },
  { id: "f-mstr-sold", claim: "In June 2026 Strategy sold 32 BTC — a break from its 'never sell bitcoin' stance", loadBearing: true, source: "decrypt / bitcoinworld", confidence: "medium", asOf: "2026-06", note: "32 BTC is trivially small in dollars. Its entire significance is symbolic — the policy broke, not the balance sheet." },
  { id: "f-mstr-defence", claim: "Strategy built a cash reserve covering 2.5+ years of debt and dividends; Saylor claims it can cover $6bn of debt even at $8,000 BTC", loadBearing: false, source: "decrypt", confidence: "medium", asOf: "2026-02", note: "The steel-man. Include it — the forced-seller thesis is weaker than it looks." },
  { id: "f-correlation", claim: "Bitcoin's correlation with the Nasdaq 100 and S&P 500 sits in the 0.70–0.80 range in risk-on conditions", loadBearing: true, source: "quasa.io, arxiv 2501.09911", confidence: "medium", asOf: "2026" },
  { id: "f-yields", claim: "The 10-year Treasury yield approached a one-year high near 4.5% in March 2026; the 30-year hit 5% in April 2026", loadBearing: true, source: "coindesk 2026-03-27, 2026-04-30", confidence: "high", asOf: "2026-04-30" },
  { id: "f-macro-cause", claim: "Analysts attribute price pressure to rising Treasury yields, a stronger dollar, tariffs, geopolitical tension and Fed policy — outweighing regulatory progress", loadBearing: true, source: "coinpedia, investing.com", confidence: "medium", asOf: "2026" },
  { id: "f-supply-2pct", claim: "Long-term holders added ~380,000 BTC (~$24.3bn, almost 2% of supply) over a 30-day window in mid-2026", loadBearing: false, source: "CryptoQuant via search", confidence: "medium", asOf: "2026-08", note: "Contradicts the distribution story if read carelessly — see unknowns. Accumulation resumed AFTER the drawdown." },
  { id: "f-m2-divergence", claim: "Global M2 grew more than 12% over the last twelve months while Bitcoin fell roughly 12% — the liquidity relationship broke down through 2026", loadBearing: true, source: "CF Benchmarks; Onramp research", confidence: "medium", asOf: "2026-08-11", note: "Follow-up round 1 replaced f-liquidity with this. Stronger, and it argues the same thesis." },
  { id: "f-whale-absorb", claim: "Wallets holding over 1,000 BTC accumulated roughly 270,000 BTC in the 30 days to 23 April 2026, and again in late June/early July while price fell below $58,000", loadBearing: true, source: "CryptoQuant via aggregators", confidence: "medium", asOf: "2026-08-11", note: "Follow-up round 1." },
  { id: "f-midtier-distribute", claim: "Holders of 100-1,000 BTC distributed about 77,800 BTC, over a window the sources do not agree on", loadBearing: true, source: "on-chain cohort analysis via aggregators", sources: [{ name: "on-chain cohort analysis via aggregators", evidenceClass: "aggregator" }], kind: "found", unit: "BTC", period: "UNRESOLVED - see note", confidence: "low", confidenceNote: "Downgraded from medium: the window is unresolved and the original comparison was arithmetically false.", asOf: "2026-08-11", contests: ["f-whale-absorb"], note: "CORRECTED 2026-08-12 by the gauntlet control migration. The original read \"about 77,800 BTC over the same 60-day window - slightly more than the whale cohort absorbed\": two arithmetic errors in one load-bearing sentence. The sibling f-whale-absorb dates its window at 30 days, not 60; and 77,800 is 29% of ~270,000, not \"slightly more\". It shipped into three scripts and fed c-scarcity-not-a-floor at leap:near. The cohort figure is kept because it is sourced; the comparison is gone because it was never true. This is the fact that forced facts[].unit/period and the arithmetic quality-bar row." },
];
