"use client";

// /kit — the Almanac world's design guidelines and the specimen the next builders
// read to learn what exists. Four modules on one rail: Identity (mark, palette,
// type, marks, motion), Law (the rules and where each is held), Parts (every export
// of components/kit and components/ui/signal in each state), Migration (declared
// intent beside the measured census). Data lives in catalog.ts, migrationMap.ts and
// census.json (generated by pipeline/kit-census.mts); this file only lays them out.

import { useEffect, useState } from "react";

import { PageHead, TabRail, Tag } from "@/components/kit";
import { Mark } from "@/components/kit/brand";
import StudioFrame from "@/components/ui/StudioFrame";

import type { Census } from "@/pipeline/kit-census.mjs";

import census from "./census.json";
import { migrationGaps } from "./migrationMap";
import { PART_COUNT, RULES, kitModuleForHash, type KitModuleId } from "./catalog";
import { Identity } from "./Identity";
import { Law } from "./Law";
import { Migration } from "./Migration";
import { Parts } from "./Parts";
import "./kit-route.css";

type Module = KitModuleId;

/** Computed from the census, so the amber tally is a measurement, not a list someone kept. */
const GAP_COUNT = migrationGaps(census satisfies Census).length;

export default function KitView() {
  const [tab, setTab] = useState<Module>("identity");

  // A module is addressable: /kit#parts opens the specimen sheet, and so does a
  // part-group jump link (/kit#g-forms), which then scrolls to its group once the
  // Parts tab has mounted.
  useEffect(() => {
    const fromHash = () => {
      const m = kitModuleForHash(window.location.hash);
      if (!m) return;
      setTab(m);
      const h = window.location.hash.replace("#", "");
      if (h !== m) {
        // Two frames: the first lets React commit the tab, the second finds the anchor.
        requestAnimationFrame(() =>
          requestAnimationFrame(() => document.getElementById(h)?.scrollIntoView()),
        );
      }
    };
    fromHash();
    window.addEventListener("hashchange", fromHash);
    return () => window.removeEventListener("hashchange", fromHash);
  }, []);

  const select = (id: Module) => {
    setTab(id);
    window.history.replaceState(null, "", `#${id}`);
  };

  return (
    <StudioFrame world="almanac" crumbs={[{ label: "Projects", href: "/projects" }, { label: "Kit" }]}>
      <PageHead
        eyebrow="Design guidelines · Almanac"
        title="Kit"
        figure={<Mark size={72} title="Gravitone" />}
        caption={<Tag>specimen</Tag>}
      />
      <TabRail
        label="kit modules"
        active={tab}
        onSelect={select}
        tabs={[
          { id: "identity", label: "Identity", panelId: "kit-panel" },
          { id: "law", label: "Law", panelId: "kit-panel", tally: { value: RULES.length } },
          { id: "parts", label: "Parts", panelId: "kit-panel", tally: { value: PART_COUNT } },
          { id: "migration", label: "Migration", panelId: "kit-panel", tally: { value: GAP_COUNT, tone: GAP_COUNT ? "amber" : "neutral" } },
        ]}
      />
      <div id="kit-panel" role="tabpanel" aria-label={tab}>
        {tab === "identity" && <Identity />}
        {tab === "law" && <Law />}
        {tab === "parts" && <Parts />}
        {tab === "migration" && <Migration />}
      </div>
    </StudioFrame>
  );
}
