// THE MIGRATION MAP, rendered: declared intent (migrationMap.ts `needs`) beside what
// the tree measures (census.json, generated by pipeline/kit-census.mts). A gap is a
// needed part the module does not use while a hand-rolled copy of it is present;
// it is computed, never typed, so the amber tally on the rail cannot rot.

import { DataTable, Ghost, Kicker, Stats, Tally } from "@/components/kit";
import type { Census, SuspectKind } from "@/pipeline/kit-census.mjs";

import census from "./census.json";
import { MODULES, measured, migrationGaps } from "./migrationMap";

const CENSUS: Census = census;

/** Census modules that are the kit itself: they render every part by design. */
const KIT_ZONE = new Set(["app/kit", "components/kit", "components/ui/signal"]);

function SuspectTallies({ suspects, amber }: { suspects: Record<SuspectKind, number>; amber: ReadonlySet<string> }) {
  const kinds = (Object.keys(suspects) as SuspectKind[]).filter((k) => suspects[k] > 0);
  if (kinds.length === 0) return <span className="k-num">0</span>;
  return (
    <span className="kr-gaps">
      {kinds.map((k) => (
        <Tally key={k} value={suspects[k]} label={k} tone={amber.has(k) ? "amber" : "neutral"} />
      ))}
    </span>
  );
}

export function Migration() {
  const gaps = migrationGaps(CENSUS);
  const claimed = new Set(MODULES.flatMap((m) => m.paths));
  const unclaimed = Object.keys(CENSUS.modules).filter((p) => !claimed.has(p) && !KIT_ZONE.has(p));
  const rows = MODULES.map((m) => ({ row: m, facts: measured(m, CENSUS), gaps: gaps.filter((g) => g.module === m.module) }));
  return (
    <div className="kr-page">
      <section className="kr-section" aria-labelledby="kr-mods">
        <Kicker>Modules</Kicker>
        <h2 id="kr-mods">What each needs, and what it uses</h2>
        <Stats
          items={[
            { n: MODULES.length, label: "modules" },
            { n: rows.reduce((n, r) => n + r.facts.files, 0), label: "source files" },
            { n: gaps.length, label: "gaps" },
            { n: CENSUS.zeroAdopters.length, label: "parts unused" },
          ]}
        />
        <DataTable
          head={["Module", "Path", "Files", "Kit", "Signal", "Suspects", "Uses", "Not yet"]}
          rows={rows.map(({ row, facts, gaps: own }) => {
            const gapParts = new Set<string>(own.map((g) => g.part));
            return [
              row.module,
              <span key="p" className="kr-path">{row.paths.join(", ")}</span>,
              <span key="f" className="k-num">{facts.files}</span>,
              <span key="k" className="k-num">{facts.kitImports}</span>,
              <span key="s" className="k-num">{facts.signalImports}</span>,
              <SuspectTallies key="x" suspects={facts.suspects} amber={new Set(own.map((g) => g.kind))} />,
              <span key="u" className="kr-parts">
                {row.needs.filter((n) => facts.parts.has(n)).map((n) => (
                  <span key={n}>{n}</span>
                ))}
              </span>,
              <span key="n" className="kr-gaps">
                {row.needs.filter((n) => !facts.parts.has(n)).map((n) =>
                  gapParts.has(n) ? (
                    <span key={n} className="kr-gap">{n}</span>
                  ) : (
                    <span key={n} className="kr-parts"><span>{n}</span></span>
                  ),
                )}
              </span>,
            ];
          })}
        />
      </section>
      <section className="kr-section" aria-labelledby="kr-unclaimed">
        <Kicker>Unclaimed</Kicker>
        <h2 id="kr-unclaimed">Modules with no declared needs</h2>
        {unclaimed.length === 0 ? (
          <Ghost shape="row" label="no unclaimed modules" />
        ) : (
          <DataTable
            head={["Path", "Files", "Kit", "Signal", "Suspects"]}
            rows={unclaimed.map((p) => {
              const m = CENSUS.modules[p];
              return [
                <span key="p" className="kr-path">{p}</span>,
                <span key="f" className="k-num">{m.files}</span>,
                <span key="k" className="k-num">{m.kitImports}</span>,
                <span key="s" className="k-num">{m.signalImports}</span>,
                <SuspectTallies key="x" suspects={m.suspects} amber={new Set()} />,
              ];
            })}
          />
        )}
      </section>
      <section className="kr-section" aria-labelledby="kr-zero">
        <Kicker>Adoption</Kicker>
        <h2 id="kr-zero">
          Parts no surface renders <Tally value={CENSUS.zeroAdopters.length} of={Object.keys(CENSUS.parts).length} label="parts" />
        </h2>
        {CENSUS.zeroAdopters.length === 0 ? (
          <Ghost shape="row" label="every part has an adopter" />
        ) : (
          <span className="kr-parts">
            {CENSUS.zeroAdopters.map((n) => (
              <span key={n}>{n}</span>
            ))}
          </span>
        )}
      </section>
    </div>
  );
}
