"""Does the character survive being animated -- within a clip, and across a cut?

    python motion.py --lane ref2va     # every clip references the same hero face
    python motion.py --lane chain      # clip N starts on clip N-1's last frame

The stills spike (CONSISTENCY-FINDINGS.md) answered the still question: a hero
reference admitted late in the denoise holds one character across three camera
setups at the real-film floor. This asks the two questions stills cannot.

  WITHIN a clip.  A new failure mode that the stills lane could not see at all:
      the face at t=0 and the face at t=3s are generated by the same pass, and
      they still drift. Cheap to measure, and it bounds how long a shot can run.

  ACROSS a cut.   The trailer question. Two techniques, and the brief expects
      them to fail differently:

      ref2va   Every clip conditioned on the same hero face. Does not care
               whether clips are adjacent, so it is the one that could scale to
               thirty shots. Needs the Ref2VA checkpoint (~21 GB, fetched by
               `fetch_ref2va.py`) -- the one thing in this whole spike that was
               genuinely not on the disk.

      chain    Clip N's first frame is clip N-1's last frame (FL2VA). Proven to
               work mechanically. Expected to hold beautifully through
               *continuous action* and to break at a hard cut, because the
               technique has nothing to say about a camera that jumped. Clips 2
               and 3 below are deliberate hard cuts, so the lane is built to
               find its own boundary rather than to flatter itself.

Frames are pulled straight out of the decoded batch with `ImageFromBatch` and
saved as PNGs, so scoring needs no ffmpeg and reads the exact pixels the model
produced. The clip is also written as video, because the identity ruler cannot
see temporal judder and a human watching it can.

Scoring stays in `identity.py` against the same real-film scale -- floor 0.364,
different-actor ceiling 0.625 -- which transfers unchanged because it is a face
ruler and a frame is a face.

OPS, the expensive kind: **Flux 2 and H3 cannot both be loaded.** This stage
recycles ComfyUI before it starts so the card and the host are clear of whatever
`consistency.py` left behind. Every failure here presents as silence, so read
the redirected stderr before reading symptoms.
"""

import argparse
import json
import shutil
import sys
import time
import urllib.request
from pathlib import Path

sys.path.insert(0, str(Path(__file__).parent))
import guard  # noqa: E402
from consistency import CHARACTER, LOCATION, SEED, generate, stage_reference  # noqa: E402

HERE = Path(__file__).parent
SHOTS = HERE / "shots"
CLIPS = HERE / "clips"
COMFY_OUT = Path(r"C:\Users\kazda\ComfyUI\output")

REF2VA = "minimax_h3_ref2va_pruned_fp8_scaled.safetensors"
FL2VA = "minimax_h3_fl2va_pruned_fp8_scaled.safetensors"
REF_LORA = "minimax_h3_ref2v_turbo_4step_v0.1_comfyui_bf16.safetensors"
FL_LORA = "minimax_h3_fl2v_turbo_8step_v1.0_comfyui_bf16.safetensors"
TEXT_ENC = "qwen3vl_32b_minimax_h3_nvfp4_awq.safetensors"
VIDEO_VAE = "minimax_h3_video_vae_fp16.safetensors"
AUDIO_VAE = "minimax_h3_audio_vae_fp32.safetensors"

# H3 accepts lengths congruent to 5 mod 17 -- the template's own expression,
# max(5, round(s*24)) + (5 - (n % 17)) % 17, only ever lands there. 73 frames is
# a little over three seconds at 24 fps, long enough for drift to show and short
# enough to run several lanes in an evening.
LENGTH = 73
FPS = 24

# Three beats in one place. Clip 1 is what the chain lane is good at -- a single
# continuous move. Clips 2 and 3 are hard cuts to camera positions the previous
# clip never saw, which is precisely where chaining is expected to give up.
BEATS = [
    ("01-turn", "Medium shot. She stands still and turns her head slowly toward the shaft of "
                "light, chin lifting. The camera holds. Dust drifts through the beam."),
    ("02-walk", "Hard cut to a low wide shot from the far end of the hangar. She walks toward "
                "camera through the shaft of light, small in frame, boots on concrete."),
    ("03-look", "Hard cut to a tight low-angle close-up from her left. She looks up, eyes "
                "narrowing, the blown-out roof light behind her head."),
]


def prompt_for(beat, ref_tag=False):
    """The same character and location clauses the stills lane used, verbatim.

    `<Picture 1>` is how H3 is told which reference is which; the node's own
    description says to use the same tags when prompting, and a reference the
    prompt never names is a reference the model is free to ignore.
    """
    ref = ("Use <Picture 1> as the reference for the woman's face and clothing. " if ref_tag else "")
    return (f"{ref}{beat} The subject is {CHARACTER}. The setting is {LOCATION}. "
            f"Photographic, 35mm cinema, natural skin texture, no text, no watermark.")


def _tail(w, model_node, cond, latent, steps, sampler, prefix, length):
    """Sampler, decode, three saved frames and a video -- shared by both lanes."""
    w["40"] = {"class_type": "KSamplerSelect", "inputs": {"sampler_name": sampler}}
    w["41"] = {"class_type": "BasicScheduler",
               "inputs": {"model": model_node, "scheduler": "simple",
                          "steps": steps, "denoise": 1.0}}
    w["42"] = {"class_type": "RandomNoise", "inputs": {"noise_seed": SEED}}
    w["43"] = {"class_type": "BasicGuider", "inputs": {"model": model_node, "conditioning": cond}}
    w["44"] = {"class_type": "SamplerCustomAdvanced",
               "inputs": {"noise": ["42", 0], "guider": ["43", 0], "sampler": ["40", 0],
                          "sigmas": ["41", 0], "latent_image": latent}}
    w["45"] = {"class_type": "VAELoader", "inputs": {"vae_name": VIDEO_VAE}}
    w["46"] = {"class_type": "VAEDecode", "inputs": {"samples": ["44", 0], "vae": ["45", 0]}}
    # First, middle and last frame as PNGs. The ruler reads these; the video is
    # for the human check, which is the part that catches what the ruler cannot.
    for tag, idx in (("a-first", 0), ("b-mid", length // 2), ("c-last", length - 1)):
        n = f"5{idx:03d}"
        w[n] = {"class_type": "ImageFromBatch",
                "inputs": {"image": ["46", 0], "batch_index": idx, "length": 1}}
        w[f"6{idx:03d}"] = {"class_type": "SaveImage",
                            "inputs": {"images": [n, 0], "filename_prefix": f"{prefix}_{tag}"}}
    w["70"] = {"class_type": "CreateVideo", "inputs": {"images": ["46", 0], "fps": FPS}}
    w["71"] = {"class_type": "SaveVideo",
               "inputs": {"video": ["70", 0], "filename_prefix": prefix,
                          "format": "auto", "codec": "auto"}}
    return w


def ref2va_workflow(prompt, ref_name, width, height, length, steps, prefix, lora=True):
    """Reference-conditioned: the hero face goes to every clip, adjacent or not."""
    w = {
        "1": {"class_type": "UNETLoader",
              "inputs": {"unet_name": REF2VA, "weight_dtype": "default"}},
        "2": {"class_type": "CLIPLoader",
              "inputs": {"clip_name": TEXT_ENC, "type": "minimax", "device": "default"}},
        "3": {"class_type": "VAELoader", "inputs": {"vae_name": VIDEO_VAE}},
        "4": {"class_type": "VAELoader", "inputs": {"vae_name": AUDIO_VAE}},
        "10": {"class_type": "LoadImage", "inputs": {"image": ref_name}},
        "11": {"class_type": "MiniMaxH3ReferenceToVideo",
               "inputs": {"clip": ["2", 0], "vae": ["3", 0], "audio_vae": ["4", 0],
                          "prompt": prompt, "width": width, "height": height,
                          "length": length, "ref_image_size": "match",
                          "ref_images.ref_image_0": ["10", 0]}},
    }
    model = ["1", 0]
    if lora:
        w["12"] = {"class_type": "LoraLoaderModelOnly",
                   "inputs": {"model": model, "lora_name": REF_LORA, "strength_model": 1.0}}
        model = ["12", 0]
    return _tail(w, model, ["11", 0], ["11", 1], steps, "res_multistep", prefix, length)


def chain_workflow(prompt, first_frame, width, height, length, steps, prefix, lora=True):
    """First/last-frame: this clip starts exactly where the previous one stopped."""
    w = {
        "1": {"class_type": "UNETLoader",
              "inputs": {"unet_name": FL2VA, "weight_dtype": "default"}},
        "2": {"class_type": "CLIPLoader",
              "inputs": {"clip_name": TEXT_ENC, "type": "minimax", "device": "default"}},
        "3": {"class_type": "VAELoader", "inputs": {"vae_name": VIDEO_VAE}},
        "10": {"class_type": "LoadImage", "inputs": {"image": first_frame}},
        "11": {"class_type": "MiniMaxH3ImageToVideo",
               "inputs": {"clip": ["2", 0], "vae": ["3", 0], "prompt": prompt,
                          "width": width, "height": height, "length": length,
                          "first_frame": ["10", 0]}},
    }
    model = ["1", 0]
    if lora:
        w["12"] = {"class_type": "LoraLoaderModelOnly",
                   "inputs": {"model": model, "lora_name": FL_LORA, "strength_model": 1.0}}
        model = ["12", 0]
    return _tail(w, model, ["11", 0], ["11", 1], steps, "res_multistep", prefix, length)


def collect(prefix, dest, length):
    """Pull this clip's saved frames and video out of ComfyUI's output tree."""
    got = {}
    for tag, idx in (("a-first", 0), ("b-mid", length // 2), ("c-last", length - 1)):
        hits = sorted(COMFY_OUT.glob(f"{prefix}_{tag}*.png"))
        if hits:
            d = dest / f"{prefix.split('-', 1)[-1]}_{tag}.png"
            shutil.copyfile(hits[-1], d)
            got[tag] = d
    for v in sorted(COMFY_OUT.rglob(f"{prefix}*.mp4")):
        shutil.copyfile(v, dest / v.name)
        break
    return got


def run(lane, width, height, length, steps, lora, hero, timeout=7200):
    out = CLIPS / lane
    out.mkdir(parents=True, exist_ok=True)
    # Flux 2 and H3 cannot co-reside. Start from a clean engine rather than
    # discovering it the slow way, as a stalled queue with no exception.
    guard.recycle_comfy("switching from Flux 2 to H3")

    ref_name = stage_reference(hero)
    print(f"  hero reference staged as {ref_name}")
    prev_last = None

    for i, (name, beat) in enumerate(BEATS):
        dest_probe = out / f"{name}_c-last.png"
        if dest_probe.exists():
            print(f"  {name}: already generated, skipping")
            prev_last = dest_probe
            continue
        # Recycle before *every* clip, not only when host memory complains.
        # A finished clip leaves ~20 GB on the card and `headroom_ok()` cannot
        # see that -- it watches RAM and commit, both of which looked fine when
        # clip 2 died of VRAM exhaustion. Against a multi-minute generation a
        # 30-second engine restart is free, so this buys reliability for nothing.
        if i > 0 or not guard.vram_ok():
            guard.recycle_comfy(f"fresh engine for {name}")
        prefix = f"{lane}-{name}"
        t = time.time()
        if lane == "ref2va":
            wf = ref2va_workflow(prompt_for(beat, ref_tag=True), ref_name,
                                 width, height, length, steps, prefix, lora)
        else:
            src = hero if prev_last is None else prev_last
            wf = chain_workflow(prompt_for(beat), stage_reference(src),
                                width, height, length, steps, prefix, lora)
        # Clips get slower as a lane proceeds even on a fresh engine -- measured
        # 1243s, 1642s, then past 2400s for identical work at 832x480x73. The
        # third clip timed out and its job vanished from history, costing the
        # whole 40 minutes. Budget generously: a client that gives up early
        # throws away work the GPU has already done.
        generate(wf, timeout=timeout)
        got = collect(prefix, out, length)
        prev_last = got.get("c-last")
        print(f"  {name}: {time.time() - t:.0f}s -> {len(got)} frames"
              f"{' + video' if any(out.glob(prefix + '*.mp4')) else ''}")

    (out / "lane.json").write_text(json.dumps({
        "lane": lane, "seed": SEED, "steps": steps, "lora": lora,
        "width": width, "height": height, "length": length, "fps": FPS,
        "hero": str(hero), "character": CHARACTER, "location": LOCATION,
        "beats": {n: prompt_for(b, ref_tag=(lane == "ref2va")) for n, b in BEATS},
    }, indent=2), encoding="utf-8")
    print(f"\n  lane written to {out}\n  now score it:  python identity.py --set clips/{lane}")


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--lane", required=True, choices=["ref2va", "chain"])
    ap.add_argument("--width", type=int, default=1344)
    ap.add_argument("--height", type=int, default=768)
    ap.add_argument("--length", type=int, default=LENGTH)
    ap.add_argument("--steps", type=int, default=4)
    ap.add_argument("--timeout", type=int, default=7200, help="seconds per clip")
    ap.add_argument("--no-lora", action="store_true", help="full steps, no turbo LoRA")
    ap.add_argument("--hero", default=str(SHOTS / "reference" / "00-hero.png"),
                    help="the still every clip is held against")
    args = ap.parse_args()
    if args.length % 17 != 5:
        print(f"  warning: H3 lengths are 5 mod 17; {args.length} is not "
              f"({args.length % 17}). Nearest valid: "
              f"{args.length - (args.length % 17) + 5}")
    run(args.lane, args.width, args.height, args.length,
        args.steps if not args.no_lora else max(args.steps, 20),
        not args.no_lora, Path(args.hero), timeout=args.timeout)


if __name__ == "__main__":
    main()
