// No tracked source names one machine's home directory.
//
// The GPU box's paths were written into the pipeline as literals -
// `C:\Users\<name>\kiro\personas\.env` for vendor keys, `C:\Users\<name>\ComfyUI`
// for the image stack, lane records pointing at that box's checkout. On any
// other machine a key lookup silently found nothing and a ComfyUI path pointed
// at a directory that does not exist (moonshot backlog Q7, 2026-10-05).
//
// Population: every tracked source or data file (code, shell, JSON) - derived
// from git. Run logs are records of what happened on a machine and are allowed
// to name it. The rule is the pattern, not a user name: the next machine's
// literal is caught the same way.
import { execFileSync } from "node:child_process";
import { readFileSync } from "node:fs";
import path from "node:path";

import { test, expect } from "@playwright/test";

const ROOT = path.resolve(__dirname, "../..");
const CODE = /\.(py|sh|ts|tsx|mts|mjs|js|json)$/;
// A Windows or POSIX home directory with a concrete user segment.
const HOME = /(?:[A-Za-z]:[\\/]{1,2}Users[\\/]{1,2}|\/home\/)(?!<|\$|%|\{)[A-Za-z0-9._-]+[\\/]/;

/** Files that may carry one, each with its reason. Kept honest by the first
 *  test: an entry whose file no longer matches is stale and fails. */
const DECLARED: Record<string, string> = {
  "context-map.json": "generated by the Personas app from its database; never hand-edited (CLAUDE.md)",
  ".personas/skill-registry.json": "a Personas app snapshot of the machine that last scanned",
  "tests/golden-path/articles-critique.probe.spec.ts": "inputs to scrubHomePaths, the function that removes these",
};

function hitsByFile(): Map<string, string[]> {
  const files = execFileSync("git", ["ls-files"], { cwd: ROOT, encoding: "utf8" })
    .split(/\r?\n/)
    .filter((f) => CODE.test(f) && !f.includes("/logs/") && !f.startsWith("node_modules/") && f !== "package-lock.json");
  expect(files.length, "the git walk read nothing").toBeGreaterThan(200);
  const hits = new Map<string, string[]>();
  for (const f of files) {
    let src: string;
    try {
      src = readFileSync(path.join(ROOT, f), "utf8");
    } catch {
      continue;
    }
    src.split(/\r?\n/).forEach((line, i) => {
      if (HOME.test(line)) hits.set(f, [...(hits.get(f) ?? []), `${f}:${i + 1}`]);
    });
  }
  return hits;
}

test("every declared exception still needs to be one", () => {
  const hits = hitsByFile();
  expect(Object.keys(DECLARED).filter((f) => !hits.has(f))).toEqual([]);
});

test("no tracked source or data file hard-codes a machine's home directory", () => {
  const hits = [...hitsByFile()].filter(([f]) => !(f in DECLARED)).flatMap(([, at]) => at);
  // This file states the pattern in prose only; nothing here matches it.
  expect(hits).toEqual([]);
});
